# $Id$
include ../makefile.defs
PACKAGE=bootstrap
PACKAGE_JS_DIR=dist/js

all:: $(PACKAGE_JS_PATH)
	echo -- make --
	$(MAKE_JS_INSTALL_DIR)
	$(INSTALL_JS)

clean::
	echo -- make clean --
	$(RM_PACKAGE)
