# $Id:
include ../makefile.defs
PACKAGE=fullcalendar

all:: $(PACKAGE_JS_PATH) $(PACKAGE_CSS_PATH)
	$(MAKE_JS_INSTALL_DIR)
	$(MAKE_CSS_INSTALL_DIR)
	$(INSTALL_JS)
	$(INSTALL_CSS)

clean::
	$(RM_PACKAGE)
